[general]
seed = 1234
xformers = true
cache_latents = true
max_token_length = 75
save_precision = "fp16"
mixed_precision = "fp16"
weighted_captions = false
gradient_checkpointing = true
network_module = "networks.lora"

[additional_network_arguments]
conv_dim = 4
conv_alpha = 1.0
network_dim = 32
network_alpha = 16
max_data_loader_n_workers = 8

[training_arguments]
clip_skip = 2
lowram = false
xformers = true
min_snr_gamma = 5.0
train_batch_size = 12
max_train_epochs = 50
max_token_length = 75
save_last_n_epochs = 50
save_every_n_epochs = 1
save_precision = "fp16"
mixed_precision = "fp16"
max_data_loader_n_workers = 8
persistent_data_loader_workers = true

[optimizer_arguments]
lr_warmup_steps = 0
learning_rate = 0.00001
optimizer_type = "AdamW8bit"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_num_cycles = 3

[model_arguments]
v2 = false
prior_loss_weight = 1.0
v_parameterization = false
pretrained_model_name_or_path = "models/sd-v1-5-pruned-noema-fp16.safetensors"

[saving_arguments]
logging_dir = "./logs"
output_name = "5_selected"
save_model_as = "safetensors"
output_dir = "output/lora/v15/c3Lier/few_shot"
